import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import NavBarComponent from "@/components/shared/nav-bar.component";
import Footer from "@/components/shared/footer.component";
import SideCartDrawerComponent from "@/components/shared/cart-drawer.component";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <head>
        <Script id='tag-manager'
        dangerouslySetInnerHTML={
          { __html: `(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
          new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
          j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
          'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
          })(window,document,'script','dataLayer','GTM-W4PPLW2');`}
        } />
        <Script
          id='clarityScript'
          dangerouslySetInnerHTML={
            {
              __html: `(function(c,l,a,r,i,t,y){
                        c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
                        t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
                        y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
                    })(window, document, "clarity", "script", "imw8vbk3te");`,
            }}
        />
        <Script id='googleAnalitycs'
          dangerouslySetInnerHTML={
            {
              __html: `window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-6R2P5JT4NX');`}}
        />
        <meta name="google-site-verification" content="S-MABBGjddcLo8_kNkNfuqVi7etsoBNnLSR-OpHJBeg" />
        <link rel="shortcut icon" href="/images/corporate/smart.webp" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-full`}
      >
        <NavBarComponent isLogued={false} avatarUrl={undefined} cartItemsCount={0} onCartClick={undefined} />
        {/* <SideCartDrawerComponent open={false} onClose={() => {}} />
         */}
        {children}
        <Footer />
      </body>
    </html>
  );
}
